name: link_rich_text
description: Flutter plugin for hyperlinks and custom special characters rich text display.
version: 2.0.0
homepage: https://github.com/chenhongchen/link_rich_text

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
